version: '3.5'
services:
  database:
    ports:
      - "3306:3036"
    environment:
      MYSQL_ROOT_PASSWORD: RootPassword
      MYSQL_DATABASE: gestao_usuarios
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
volumes:
  db-volume: